name: Docker Build

on:
  push:
    branches: [ "master", "proposed_master" ]
  pull_request:
    branches: [ "master", "proposed_master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
      
    - uses: actions/checkout@v3

    - name: Run test command
      run: make docker-test
