name: Docker Build

on:
  push:
    branches: [ "master", "proposed_master" ]
  pull_request:
    branches: [ "master", "proposed_master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run test command
      run: make docker-test
